### PR TITLE
MassInstallAction: Install the CI workflow on this repository

### PR DESCRIPTION
**Pull request by timholy**
This pull request sets up the CI workflow on this repository.

### CODE REVIEW

**Comment by mkitti** [comment]
OK. Note that I cannot merged this because it depends Travis passing... which will not happen because we removed the configuration.

**Comment by timholy** [comment]
I've at least temporarily turned that off.

I vote that you should be given full admin access. Let's see if @tomasaschan wants to weigh in, and if no response in a few days, I'll grant it.

**Comment by timholy** [comment]
For those who may not be following, travis.org is going away and travis.com will not be free. Hence this PR.

**Comment by mkitti** [comment]
Have we tried asking Travis for open source credits?

**Comment by timholy** [comment]
Nope. Feel free to do that! I am guessing it will be hard, but honestly I have no idea. I am sure that the arrival of GitHub Actions was very hard on their bottom line.

**Comment by tomasaschan** [comment]
I have no qualms with adding more admins - the more the merrier :)

---

Side note:

There's really no good reason I should have a say in basically any decision around this library anymore. I'm lurking in the background, (sometimes) reading issues and PRs out of curiosity, but I view it as a success for both the library and the community that it is moving along without my involvement. I recently added myself as an admin on this repo specifically to be able to leave the JuliaMath organization (which I joined to be able to transfer ownership of this repo, and wanted to leave mainly to stop getting email notifications about new public keys added...) without losing access, but that was still more for sentimental reasons than anything else. In short, I don't think you should ever feel the need to ask my permission for anything :)

**Comment by timholy** [comment]
@mkitti, you now have all the powers you need. I'd endorse any solution you prefer, including closing this PR without merging it.

@tomasaschan, understood, thanks for your willingness to see this move on!

**Pull request merged**
