### PR TITLE
Mention KernelInterpolation.jl in section about other packages

### PR DESCRIPTION
**Pull request by JoshuaLampert**
I have a package [KernelInterpolation.jl](https://github.com/JoshuaLampert/KernelInterpolation.jl), which performs RBF scattered data interpolation. I added it to the list of other interpolation packages.

### CODE REVIEW

**Comment by JoshuaLampert** [comment]
Does anyone have a spare minute for a quick review?

**Comment by mkitti** [comment]
I'm trying to understand why there are multiple line changed in the diff.

**Comment by JoshuaLampert** [comment]
Gently bumping this. Should I reintroduce the trailing white spaces to have only a one-line diff?

**Comment by JoshuaLampert** [comment]
> That would help, yes.

Done.

**Comment by mkitti** [comment]
Thanks. Merged.

**Comment by JoshuaLampert** [comment]
Thanks!

**Pull request merged**
