### PR TITLE
Remove the performance warning on Union{Missing, _} values

### PR DESCRIPTION
**Pull request by cstjean**
Fix https://github.com/JuliaMath/Interpolations.jl/issues/287

### CODE REVIEW

**Comment by mkitti** [comment]
I intend to squash merge this shortly based on comments in #287, especially by @tomasaschan .

**Comment by cstjean** [comment]
👍 Thanks! This helps us a ton, we've been working around this issue internally for nearly two years.

**Comment by cstjean** [comment]
Could I ask for a release, please?

**Comment by mkitti** [comment]
Sure. Let me see if I can work out what is happening with the CompatHelper PR.

Do you need Julia 1.0 backwards compatibility?

**Comment by cstjean** [comment]
Nope, we're on 1.5

**Pull request merged**
