### PR TITLE
A small step towards 0.7 compatibility.

### PR DESCRIPTION
**Pull request by hessammehr**
Tests pass without issue on 0.6 as well.

### CODE REVIEW

**Comment by halleysfifthinc** [comment]
Travis is allowing failures on nightly; there are still a number of deprecation warnings starting for Interpolations.jl at [line 670](https://travis-ci.org/JuliaMath/Interpolations.jl/jobs/408148043#L670).

**Comment by hessammehr** [comment]
Yes, I'll keep the commits coming.

**Comment by hessammehr** [comment]
The big blocking issue is that tridiagonal matrices are `Tridiagonal{T} where T` in 0.6 and `Tridiagonal{T,V where V<:Array{T,1}}` in 0.7. This seems to affect both Interpolations.jl and AxisAlgorithms.jl. Does this seem like something that could be added to Compat.jl? The fix should be fairly simple:

```julia
const Tridiag{T} =  VERSION > v"0.7.0-DEV.1412" ? (Tridiagonal{T,V} where V<:AbstractArray{T} where T) : (Tridiagonal{T} where T)
```

**Comment by timholy** [comment]
Sorry this didn't get attention!

Interpolations is now 0.7-compatible (0.7-requiring, actually)

**Pull request closed without merging**
