### PR TITLE
Minor overhaul of markdown docs and docstrings

### PR DESCRIPTION
**Pull request by abhro**
If stayed indented, Documenter.jl picks it all up as code sample and displays monospace. Moreover, the actual code sample/examples are not recognized.

### CODE REVIEW

**Comment by abhro** [comment]
The doctests fail because `using Interpolations` isn't run for the doctests. Should that be handled in the docstrings or elsewhere in the repo?

**Comment by abhro** [comment]
Sorry, turns out renaming a branch closes the pull request.

**Comment by mkitti** [comment]
Hmm... let me see what I can do here.

**Review by mkitti — APPROVED** [review]

**Review by mkitti — APPROVED** [review]

**Comment by abhro** [comment]
Yes, it should be. Thank you!

**Pull request merged**
