### PR TITLE
 add fft-based interpolation for 1D real signals

### PR DESCRIPTION
**Pull request by gdestouet**
Simple test that I didn't included yet 

``` 
using Interpolations
N=512
new_size = 1024

sig = sin.( 2 * pi * 0.01 * N .* range(0,1,length=N) )
new_sig = interpolate(sig,FFT(new_size))
sig2 = sin.( 2 * pi * 0.01 * N .* range(0,1,length=new_size) )
```
You can check using Plots that `sig2` and `new_sig` have the same frequency

### CODE REVIEW

**Comment by tomasaschan** [comment]
For reasons outlined in https://github.com/JuliaMath/Interpolations.jl/issues/282#issuecomment-461761255, I don't think this is a good fit inside Interpolations.jl. It's a good candidate to start building a separate package (FFTInterpolations.jl?), though!

**Comment by timholy** [comment]
If Requires is acceptable, should we reopen?

**Comment by timholy** [comment]
This can't be quite right, however:
```julia
julia> using Interpolations

julia> x = rand(5)
5-element Array{Float64,1}:
 0.2475749273753287 
 0.5177360746376121 
 0.4359109842436517 
 0.2480371524923537 
 0.09161945602953914

julia> y = interpolate(x, FFT(100));

julia> using Statistics

julia> mean(y)
0.015408785947784854

julia> mean(x)
0.30817571895569706
```
interpolate

**Comment by gdestouet** [comment]
Yup, with this implementation you need to renormalize by N_new / N_old after the interpolation ( forgot to add this ).

Another thing : if you take random sample it will have an infinite bandwith thus you cant really interpolate with an FFT since it doesnt respect the Nyquist Shannon theroem.

For an example you can check the comment I made for the PR. You better try with a sinusoid with a frequency below the nyquist rate.

**Pull request closed without merging**
