### PR TITLE
Improve type promotion for SVectors in tweight()

### PR DESCRIPTION
**Pull request by maxfreu**
This fixes the first post of #359.

### CODE REVIEW

**Comment by mkitti** [comment]
Thanks. I think we may still want to constrain `T`. If it is an `AbstractFloat` then we can use the type. Otherwise, we still need need to use `float` to get the corresponding float type for `T`. @timholy, do you concur?

**Comment by maxfreu** [comment]
You mean like this?
```julia
tweight(A::AbstractArray{<:AbstractVector{T}}) where {T<:AbstractFloat} = T
```
To be honest, I'm not very familiar with the matter, so I rely on your judgement.
However interpolating between Ints seems to work and produce meaningful results, it just doesn't preserve the type.
```julia
itp = interpolate([@SVector(Int16[0,0]), @SVector(Int16[1,1])], BSpline(Linear())) # ... with eltype SArray{..., Int16,...}
typeof(itp(1f0))  # Float32
typeof(itp(Int16(1)))  # Int64
```

**Comment by mkitti** [comment]
I think we might also want this:
```julia
tweight(A::AbstractArray{<:AbstractVector{T}}) where {T<:Integer} = typeof(float(zero(T)))
```

I'm not clear that this accomplishes what you want, however.

**Comment by maxfreu** [comment]
Maybe I have to clarify what I want giving an example:
I want the element type of
```julia
itp = interpolate([@SVector(Float32[0,0]), @SVector(Float32[1,1])], BSpline(Linear()))
```
to be an `SArray{Tuple{2}, Float32, 1, 2}` instead of `SArray{Tuple{2}, Float64, 1, 2}` because this fixes the first post of #359 and (my) [downstream issue](https://github.com/Evizero/Augmentor.jl/issues/62) with Float32 interpolations in Augmentor; this would reduce memory allocation and improve speed. Having Floats with the correct bit depth would do the job; interpolating ints is a different story.

Note that unlike I first thought this is not related to calling `itp(...)`, which doesn't promote the type of its input. But code which uses the element type of the interpolation might return unexpected results.

**Comment by mkitti** [comment]
That is clearer. I will examine the issue further.

**Comment by mkitti** [comment]
This my is my current focus for this package.

**Comment by maxfreu** [comment]
Any progress on this? Making it work for 32bit floats would already be good.

**Comment by mkitti** [comment]
I am going to merge this for now, but may narrow this later if needed.

**Pull request merged**
