### PR TITLE
Update extrapolations.md

### PR DESCRIPTION
**Pull request by ric-cioffi**
Changed `Linear` to `Line`

### CODE REVIEW

**Comment by timholy** [comment]
Looks right to me. Any particular reason you closed this?

**Comment by ric-cioffi** [comment]
No, that was actually a mistake. I closed it because I thought it was wrong but I was simply working with an old version, so I think the PR was correct in the first place.

**Comment by timholy** [comment]
I can't reopen myself because it's deleted.

**Comment by ric-cioffi** [comment]
I'll open a new pull request, sorry for the mess.

**Pull request closed without merging**
