### PR TITLE
Add interp1-like interpolation modes

### LINKED ISSUE #328: Previous interpolation
Is it possible to include *previous* interpolation like in MATLAB *interp1*

> Previous neighbor interpolation. The interpolated value at a query point is the value at the previous sample grid point.

It should be a minimal change from the already existing *constant* interpolation, which is the equivalent to *nearest* interpolation in MATLAB.

### PR DESCRIPTION
**Pull request by ohmsweetohm1**
Adds `previous` and `next` interpolation to the `Constant` interpolation.

```julia
using Interpolations

x = collect(1.0:1.0:40.0)
y = rand(length(x))
itp_g1 = interpolate((x,), y, Gridded(Constant()))
itp_g2 = interpolate((x,), y, Gridded(Constant(:previous)))
itp_g3 = interpolate((x,), y, Gridded(Constant(:next)))

itp_g1.([2.1, 2.6]) # y[2] y[3]
itp_g2.([2.1, 2.6]) # y[2] y[2]
itp_g3.([2.1, 2.6]) # y[3] y[3]
```
Also works for `BSpline`.
```julia
a = 1:10
itp_b1 = interpolate(a, BSpline(Constant()))
itp_b2 = interpolate(a, BSpline(Constant(:previous)))
itp_b3 = interpolate(a, BSpline(Constant(:next)))

itp_b1.([2.1, 2.6]) # a[2] a[3]
itp_b2.([2.1, 2.6]) # a[2] a[2]
itp_b3.([2.1, 2.6]) # a[3] a[3]
```
This closes #328.

### CODE REVIEW

**Comment by timholy** [comment]
I'm worried about performance regressions; I don't think any other "simple" interpolant needs to do a runtime check of a value. Can you test?

**Comment by fabern** [comment]
I'd be interested in this. But I don't follow the remark by @timholy . What should be tested?

**Comment by ohmsweetohm1** [comment]
Seems like it does.

master:
```julia
using Interpolations
using BenchmarkTools

N = 10_000
x = Float64.(collect(1.0:1.0:N))
@benchmark interpolate((x,), y, Gridded(Constant())) setup=(y = rand(length(x)))

BenchmarkTools.Trial:
  memory estimate:  48 bytes
  allocs estimate:  2
  --------------
  minimum time:     3.573 μs (0.00% GC)
  median time:      4.960 μs (0.00% GC)
  mean time:        5.076 μs (3.58% GC)
  maximum time:     1.824 ms (99.60% GC)
  --------------
  samples:          10000
  evals/sample:     8
```

patch-1:
```julia
using Interpolations
using BenchmarkTools

N = 10_000
x = Float64.(collect(1.0:1.0:N))
@benchmark interpolate((x,), y, Gridded(Constant())) setup=(y = rand(length(x)))

BenchmarkTools.Trial:
  memory estimate:  80 bytes
  allocs estimate:  4
  --------------
  minimum time:     33.279 μs (0.00% GC)
  median time:      43.946 μs (0.00% GC)
  mean time:        45.668 μs (0.00% GC)
  maximum time:     890.025 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1

@benchmark interpolate((x,), y, Gridded(Constant(:previous))) setup=(y = rand(length(x)))

BenchmarkTools.Trial:
  memory estimate:  80 bytes
  allocs estimate:  4
  --------------
  minimum time:     33.279 μs (0.00% GC)
  median time:      40.960 μs (0.00% GC)
  mean time:        48.343 μs (0.00% GC)
  maximum time:     8.138 ms (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1

@benchmark interpolate((x,), y, Gridded(Constant(:next))) setup=(y = rand(length(x)))

BenchmarkTools.Trial:
  memory estimate:  80 bytes
  allocs estimate:  4
  --------------
  minimum time:     33.279 μs (0.00% GC)
  median time:      34.987 μs (0.00% GC)
  mean time:        41.219 μs (0.00% GC)
  maximum time:     1.498 ms (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1
```

**Comment by timholy** [comment]
Master:
```julia
julia> using Interpolations, BenchmarkTools
[ Info: Precompiling Interpolations [a98d9a8b-a2ab-59e6-89dd-64a1c18fca59]

julia> y = rand(5)
5-element Array{Float64,1}:
 0.37602777671199394
 0.6041333122279202
 0.08966655444272642
 0.30954319112308926
 0.9757132197300618

julia> itp = interpolate(y, BSpline(Constant()))
5-element interpolate(::Array{Float64,1}, BSpline(Constant())) with element type Float64:
 0.37602777671199394
 0.6041333122279202
 0.08966655444272642
 0.30954319112308926
 0.9757132197300618

julia> @btime $itp(x) setup=(x=1.0+rand())
  3.683 ns (0 allocations: 0 bytes)
```

This branch:
```julia
julia> @btime $itp(x) setup=(x=1.0+rand())
  28.640 ns (0 allocations: 0 bytes)
0.37844334921566003
```

(No, I am *not* maintaining this package...:smile:)

**Comment by ohmsweetohm1** [comment]
Sry, I totally tested the wrong thing.

**Comment by ohmsweetohm1** [comment]
```julia
julia> using Interpolations, BenchmarkTools

       y = rand(5)
       itp = interpolate(y, BSpline(Constant()))
       @btime $itp(x) setup=(x=1.0+rand())

       itp = interpolate(y, BSpline(Constant{Previous}()))
       @btime $itp(x) setup=(x=1.0+rand())

       itp = interpolate(y, BSpline(Constant{Next}()))
       @btime $itp(x) setup=(x=1.0+rand())
  4.693 ns (0 allocations: 0 bytes)
  4.693 ns (0 allocations: 0 bytes)
  5.973 ns (0 allocations: 0 bytes)
```

**Comment by mkitti** [comment]
Could we add tests for `previous` and `next`?

**Comment by mkitti** [comment]
Could we add some very simple tests for the different parameterized versions of `Constant`? We should be able to merge immediately after we have those.

**Comment by mkitti** [comment]
Thank you for the tests!

**Comment by ohmsweetohm1** [comment]
Thx for the merge. I started this a while ago (11 Nov 2019) 🙈

**Comment by mkitti** [comment]
Yes, I can see that. I really dislike long outstanding PRs. Thank you for your patience.

We've had a maintainership change here, so things will hopefully turnover more quickly now.

**Pull request merged**
